name: Assign Assignees

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
jobs:
  assign-author:
    if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
    timeout-minutes: 1
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
